### ISSUE TITLE
Problem: Build failure on Gentoo Linux using GCC 6.3.0

### ISSUE THREAD

**Issue by thunderlark** [Adolfcoin/adolfcore-zero#24]
Failed due to `-Werror=terminate: error: throw will always call terminate()`
I fixed it by modifying `CMakeLists.txt` and removing the only instance of `-Werror`, and then regenerating Makefile with `cmake .`

**Comment by thefuhrer** [comment]
Could you send a pull request with that change? Follow the Fuhrerprocess (https://github.com/Adolfcoin/Wiki/wiki/The-F%C3%BChrerprocess)

**Comment by thunderlark** [comment]
Done.

**Comment by thefuhrer** [comment]
Wunderbar! And now that this issue is resolved (it is, right?), you can close it.
